### ISSUE TITLE
multi-account containers

### ISSUE THREAD

**Issue by jettero** [arunelias/session-alive#10]
This plugin seems to be unaware of multi-account containers.

I have two microsoft outlook container tabs for two totally different accounts. All the URLs are essentially identical. It's not clear to me if the background refresh happens in either of the account containers. in which case the refresh wouldn't have the relevant cookies for either of the afflicted accounts.

**Comment by arunelias** [comment]
Currently container name/ details are ignored by the extension, as the permission to access that is not provided to it.

Thanks for the suggestion and i will certainly look into it.

**Comment by arunelias** [comment]
Thanks again for the suggestion, And Version 2.0 now supports Multi-Account Containers. Please update to Version 2.0 if not done automatically.
