### ISSUE TITLE
No Rules are running! Click the Settings button to add new rules.

### ISSUE THREAD

**Issue by ericcurtin** [arunelias/session-alive#19]
I followed the steps, went to the trigger url, doesn't seem to work

I'm running Firefox 76.0.1 (64-bit) on xubuntu 20.04

Other plugins installed include https everywhere and privacy badger.

It's outlook365 I'm using it for, company has a low idle timeout for re-logins.

**Comment by ericcurtin** [comment]
I also intend to use it for https://teams.microsoft.com/ if I can get it working

**Comment by ericcurtin** [comment]
I may have fixed it, not sure what fixed it

**Comment by ericcurtin** [comment]
Still an issue, sometimes it works, sometimes it's hopeless... There's quite a few redirects but the final page I end up on is:

https://outlook.office.com/mail/inbox

and I want it to work for that page

**Comment by ericcurtin** [comment]
It always seems to work for teams, just not outlook

**Comment by arunelias** [comment]
Hi @ericcurtin 
Hope the new version with wildcard support should help it. In the new version you can use https://*.office.com as URL. It is pushed to git for testing, will publish to Firefox soon.

**Comment by jise** [comment]
> I also intend to use it for https://teams.microsoft.com/ if I can get it working

This is the only mention of Teams within this add-on.
I would like to ask you, you mentioned that it works with Teams.
The goal is to keep your Teams session active so that your presence status is permanently Available - Green?
