### ISSUE TITLE
Will this work if you have multiple tabs

### ISSUE THREAD

**Issue by falk0069** [arunelias/session-alive#24]
I'm trying to get this to work on Azure where the tenant administrator has set an idle timeout to 15 minutes.  The problem I'm running into is if I have multiple tabs open and just one of them times out.  When this happens all of my tabs get forcefully logged out.

I believe Azure uses a javascript idle timer and the future "Background Request Advanced Options" may be a solution.  But in the meantime I'm just trying to get the Foreground Auto-Reload to work but it only seems to fire on the first tab opened. Is there a way to make it work on all tabs?

Thanks so much for creating this add-on

**Comment by arunelias** [comment]
Hi @falk0069 
One rule runs in a single tab only. I believe there are other add-ons for auto reloading tabs. Also it may trigger some sites rate limiting algorithm. If the site uses JavaScript idle timer, it is hard to overcome. Needs some R&D to see how it detects the user is inactive. Thanks a lot for reporting it.
