### ISSUE TITLE
Inhibit foreground reload if tab/window is active

### ISSUE THREAD

**Issue by jil24** [arunelias/session-alive#25]
Is it possible to inhibit foreground reload if you're actively working in the affected tab? The countdown warning is very nice and useful, but it would be excellent for it to be automatic.

**Comment by arunelias** [comment]
Hi @jil24 @peace2000 
One rule runs in a single tab, You can open a new tab and keep working on the new tab, while the reload happens in first tab. I think adding an user active detection is a complex process, and it may affect the existing functionality of the pages it run, and needs a lot of R&D. Thank you for your suggestions.
