### ISSUE TITLE
any way porting to chrome?

### ISSUE THREAD

**Issue by evakhoni** [arunelias/session-alive#32]
the chrome extension https://github.com/snytkine/staying_alive that this one got an inspiration from, [is officially dead.](https://github.com/snytkine/staying_alive/issues/24)
is there any plans porting session alive to chrome then? as many complain there isn't a direct alternative on chrome at this point

**Comment by chunheit** [comment]
^ 
If I use stricly chrome, should I just use the original staying alive?

**Comment by evakhoni** [comment]
> ^ If I use stricly chrome, should I just use the original staying alive?

issue is, its no longer alive https://github.com/snytkine/staying_alive/issues/24

**Comment by chunheit** [comment]
I believe you can download the zip and load it into chrome like the comment above yours? or does that not work anymore
https://github.com/snytkine/staying_alive/issues/24#issuecomment-777793882

**Comment by evakhoni** [comment]
well, you may still able launch it that way, lets say there are plenty of good reasons why you shouldn't.  
_p.s. its not for me, I'm on firefox@fedora_

**Comment by arunelias** [comment]
It was difficult as the extension was written from the ground up for
firefox, as the firefox API was based on promise.
Now with the new Manifest V3 of chrome, it is possible as it supports
promise. I was able to rewrite it for chrome with minor modifications.
I will commit it to git after some testing.

**Comment by evakhoni** [comment]
Nice! once ready, I'll let my chrome-using friends daily-drive it for a while, will report issues if any

**Comment by arunelias** [comment]
I have committed the code to git and submitted the addon to the Chrome webstore.
Today it was reviewed and approved. Please find the link below
https://chrome.google.com/webstore/detail/session-alive/aodfoiacnmepndhojccepdcpmehjbham

**Comment by arunelias** [comment]
It was difficult as the extension was written from the ground up for
firefox, as the firefox API was based on promise.
Now with the new Manifest V3 of chrome, it is possible as it supports
promise. I was able to rewrite it for chrome with minor modifications. I
will commit it to git after some testing.
