### ISSUE TITLE
Claims "No rules are running"

### ISSUE THREAD

**Issue by teknowledgist** [arunelias/session-alive#41]
Trying this out because it could be super useful.  I have created two rules, neither of which is disabled.  I thought it was working, but when my connection expired, I clicked on Session Alive to tweak the rule and it says "No rules are running!  You can manage the rules in the settings page" and it has a button to "Add a rule for this page" which there already is one.

What happened?  I do have an asterisk for each rule because, for example, I don't want to be signed out of a wiki regardless of which page I am on.  

Thanks!

**Comment by arunelias** [comment]
Is the rule started running while you navigated to the trigger page? It will show the number of running rules beside the icon.

**Comment by teknowledgist** [comment]
I am no longer getting the "No rules are running" message for the sites I've configure rules.  I don't know what changed other than newer versions of Firefox.  The rules seem to work at least some of the time, but also seem to not keep me logged in some of the time.  I haven't had time to test and document the difference.  

I will close this issue because the title no longer applies.  Thanks for the follow up.
