### ISSUE TITLE
Just not working at all

### ISSUE THREAD

**Issue by XceSx6** [arunelias/session-alive#6]
Dear Dev,

I've reinstalled the latest version, added my Rule again, with the same result:
- It does not show up in the DropList
- It doesn't do anything at all ..
>> Only has the base URL and a 10mins Interval and a Name, no other setup is made

![image](https://user-images.githubusercontent.com/17053283/50557917-fa6ef600-0ce9-11e9-9fe7-398c6a19d159.png)

**Comment by XceSx6** [comment]
FYI, this problem persists on a completely different environment..
The above is on PC-1 with a standard Firefox
The exact same problem is present on PC-2 running a Firefox Developer Edition

**Comment by arunelias** [comment]
Can try the quick-start mentioned in https://github.com/arunelias/session-alive#quick-start and then try your rule?

**Comment by XceSx6** [comment]
Have, to no avail ...

![image](https://user-images.githubusercontent.com/17053283/50702889-908c7e80-1052-11e9-8278-ffa970090fe7.png)

**Comment by arunelias** [comment]
Did you Navigate to the Trigger URL in a new tab?
The rule is activated when navigated/ refreshed the trigger URL in a tab. 
PFA the screenshot below. I have refreshed the trigger URL in the first tab, then the rule is activated.
![image](https://user-images.githubusercontent.com/32271975/50726303-2991c700-1131-11e9-878e-eb5d423f8bc4.png)

**Comment by XceSx6** [comment]
Well there's my problem ;)
Thanks !
