### ISSUE TITLE
Regex for rule? (aka wildcard)

### ISSUE THREAD

**Issue by LeoUfimtsev** [arunelias/session-alive#8]
Hello, 

I often hang out on a page like this:

     1 https://role.rhu.redhat.com/rol-rhu/rhz/rhls/course/jb283-1.0/pr01

But only this part is the same, the rest of the url changes as I navigate:

    2  https://role.rhu.redhat.com/rol-rhu/

The plugin works with '2' upon login, but I need to keep a tab open with '2' as the url. I can't get session-alive to work with regex-like to pick up on pattern 1.
Is there a way to specify wildcard?

**Comment by arunelias** [comment]
Hi,
The foreground page reload rule has pattern matching for the trigger URL.
The background rule does not need it, as once logged in; it is locked to the tab, not the URL; it is active till you close the tab, or navigates to another domain.
You just need to set the "trigger URL" as the URL you are landing, after you log-in to the site.

**Comment by LeoUfimtsev** [comment]
Thank you for pointing this out.  I was using a different page for the trigger (course catalogue) rather than the login page. Using the login page has indeed solved the problem.
